version: "3.8"

services:
  # MongoDB
  mongodb:
    image: mongo:latest
    command: --replSet rs0
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: password
      AUTH: admin
    ports:
      - "27017:27017"
    volumes:
      - "my_mongodb_data:/data/db"
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
  # Mongo Express
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  app:
    build:
      context: .
    container_name: express-app
    restart: always
    environment:
      PORT: 4000
      MONGO_URI: mongodb://testuser:password@mongodb:27017/admin
    ports:
      - "4000:4000"
    depends_on:
      - mongodb
    command: ["yarn", "start"]

volumes:
  my_mongodb_data:
    driver: local
